# 签到信息
Clock:
  # 签到状态:END 或者START
  state: START
  # 国家
  country: 中国
  # 详细地址
  address: 内蒙古包头市东河区沙尔沁镇莎木佳村
  # 省份
  province: 内蒙古自治区
  # 地区
  city: 包头市
  # 纬度
  latitude: 40.569756
  # 经度
  longitude: 110.326876
