# 签到信息
Clock:
  # 签到状态:END 或者START
  state: START
  # 国家
  country: 中国
  # 详细地址
  address: 上海博为峰长沙分公司
  # 省份
  province: 湖南省
  # 地区
  city: 长沙市
  # 纬度
  latitude: 28.201277
  # 经度
  longitude: 112.988118
