## run.yml
name: "run"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # // 分钟 小时 日期 月份 星期  每个小时的第20分钟执行
    - cron: 30 0 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: "Checkout codes" # 步骤一，获取仓库代码
        uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "安装模块" # 步骤二，执行sh命令文件
        run: |
         pip install -r app/requirements.txt 
      - name: "开始签到"
        run: |
          echo "开始签到"

          cd app

          python main.py
        env:
          user: "${{secrets.USER}}"
          pwd: "${{secrets.PWD}}"
